### ISSUE TITLE
System.TypeException: Invalid date/time 

### ISSUE THREAD

**Issue by pgonzaleznetwork** [RetekBacsi/TestDataLoader#2]
I'm trying to set a Date/Time field using this format

`<CreatedDate>2021-05-01T10:00:00.000+0000</CreatedDate>`

And I get the following error:

`System.TypeException: Invalid date/time `

I tried removing the + and make it this

`<CreatedDate>2021-05-01T10:00:00.000</CreatedDate>`

and it still fails.

This format is allowed in the `Test.loadData()` standard method. 

It would be great if the library supported this format to have feature parity with the `Test.loadData()`

From reading this question, you may need to use a JSON parser to parse these dates

https://salesforce.stackexchange.com/questions/247210/system-typeexception-invalid-date-time-2019-01-03t002601-711-0200

**Comment by pgonzaleznetwork** [comment]
Also if you want I can try to fix this myself and submit a pull request.

**Comment by RetekBacsi** [comment]
You can try the current version, it falls back to JSON parser when the standard DateTime.valueOf call fails.

**Comment by pgonzaleznetwork** [comment]
Works now, thanks!
